[[constraint]]
  name = "github.com/soniakeys/sexagesimal"
  version = "1.0.0"

[[constraint]]
  name = "github.com/soniakeys/unit"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
